server {
    listen 80;
    server_name *.storekit.dev;

    location / {
        proxy_pass 172.18.0.7p;  # Replace with your Laravel app's internal Docker IP or service name
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
